CREATE TABLE [dbo].[PushClientDetail] (
    [PushClientDetailId]          INT             IDENTITY (1, 1) NOT NULL,
    [ClientWebhookId]             INT             NULL,
    [IsSynced]                    BIT             CONSTRAINT [DF_PushClientDetail_IsSynced] DEFAULT ((0)) NULL,
    [SiteId]                      INT             NULL,
    [ClientId]                    NVARCHAR (30)   NULL,
    [ClientUniqueId]              INT             NULL,
    [CreationDateTime]            NVARCHAR (50)   NULL,
    [Status]                      NVARCHAR (20)   NULL,
    [FirstName]                   NVARCHAR (50)   NULL,
    [LastName]                    NVARCHAR (100)  NULL,
    [MiddleName]                  NVARCHAR (100)  NULL,
    [Email]                       NVARCHAR (100)  NULL,
    [MobilePhone]                 NVARCHAR (30)   NULL,
    [HomePhone]                   NVARCHAR (30)   NULL,
    [WorkPhone]                   NVARCHAR (30)   NULL,
    [AddressLine1]                NVARCHAR (150)  NULL,
    [AddressLine2]                NVARCHAR (150)  NULL,
    [City]                        NVARCHAR (100)  NULL,
    [State]                       NVARCHAR (50)   NULL,
    [PostalCode]                  NVARCHAR (30)   NULL,
    [Country]                     NVARCHAR (50)   NULL,
    [BirthDateTime]               NVARCHAR (30)   NULL,
    [Gender]                      NVARCHAR (20)   NULL,
    [AppointmentGenderPreference] NVARCHAR (10)   NULL,
    [FirstAppointmentDateTime]    NVARCHAR (30)   NULL,
    [ReferredBy]                  NVARCHAR (100)  NULL,
    [IsProspect]                  BIT             NULL,
    [IsCompany]                   BIT             NULL,
    [IsLiabilityRelease]          BIT             NULL,
    [LiabilityAgreementDateTime]  NVARCHAR (50)   NULL,
    [HomeLocation]                INT             NULL,
    [ClientNumberOfVisitsAtSite]  INT             NULL,
    [SendAccountEmails]           BIT             NULL,
    [SendAccountTexts]            BIT             NULL,
    [SendPromotionalEmails]       BIT             NULL,
    [SendPromotionalTexts]        BIT             NULL,
    [SendScheduleEmails]          BIT             NULL,
    [SendScheduleTexts]           BIT             NULL,
    [CreditCardLastFour]          VARCHAR (4)     NULL,
    [CreditCardExpDate]           DATETIME        NULL,
    [DirectDebitLastFour]         VARCHAR (4)     NULL,
    [Notes]                       NVARCHAR (MAX)  NULL,
    [LastModifiedDateTime]        DATETIME        NULL,
    [PhotoUrl]                    NVARCHAR (1000) NULL,
    [PreviousEmail]               NVARCHAR (100)  NULL,
    CONSTRAINT [PK_PushClientDetail] PRIMARY KEY CLUSTERED ([PushClientDetailId] ASC),
    CONSTRAINT [FK_PushClientDetail_ClientWebhook] FOREIGN KEY ([ClientWebhookId]) REFERENCES [dbo].[ClientWebhook] ([ClientWebhookId])
);

