CREATE TABLE [dbo].[PushSiteLocation] (
    [PushSiteLocationId] INT             NOT NULL,
    [ClientWebhookId]    INT             NOT NULL,
    [IsSynced]           BIT             CONSTRAINT [DF_PushSiteLocation_IsSynced] DEFAULT ((0)) NULL,
    [SiteId]             INT             NULL,
    [LocationId]         INT             NULL,
    [Name]               NVARCHAR (50)   NULL,
    [Description]        NVARCHAR (100)  NULL,
    [HasClasses]         BIT             CONSTRAINT [DF_PushSiteLocation_HasClasses] DEFAULT ((0)) NULL,
    [PhoneExtension]     NVARCHAR (50)   NULL,
    [AddressLine1]       NVARCHAR (100)  NULL,
    [AddressLine2]       NVARCHAR (100)  NULL,
    [City]               NVARCHAR (50)   NULL,
    [State]              NVARCHAR (50)   NULL,
    [PostalCode]         NVARCHAR (15)   NULL,
    [Phone]              NVARCHAR (50)   NULL,
    [Latitude]           DECIMAL (11, 8) NULL,
    [Longitude]          DECIMAL (11, 8) NULL,
    [Tax1]               NUMERIC (8, 2)  NULL,
    [Tax2]               NUMERIC (8, 2)  NULL,
    [Tax3]               NUMERIC (8, 2)  NULL,
    [Tax4]               NUMERIC (8, 2)  NULL,
    [Tax5]               NUMERIC (8, 2)  NULL,
    [WebColor5]          NVARCHAR (15)   NULL,
    [DateCreated]        DATETIME        NULL,
    [TimeStamp]          ROWVERSION      NULL,
    CONSTRAINT [PK_PushSiteLocation] PRIMARY KEY CLUSTERED ([PushSiteLocationId] ASC),
    CONSTRAINT [FK_PushSiteLocation_ClientWebhook] FOREIGN KEY ([ClientWebhookId]) REFERENCES [dbo].[ClientWebhook] ([ClientWebhookId])
);

