CREATE TABLE [dbo].[Scan] (
    [ScanId]                          INT            IDENTITY (1, 1) NOT NULL,
    [ScansImportId]                   INT            NOT NULL,
    [MemberId]                        INT            NULL,
    [MobileNumber]                    NVARCHAR (50)  NOT NULL,
    [Height]                          NUMERIC (8, 2) NULL,
    [GenderId]                        INT            NULL,
    [Age]                             INT            NULL,
    [TestDateTime]                    DATETIME       NULL,
    [Weight]                          NUMERIC (8, 2) NULL,
    [LLWeightNormalRange]             NUMERIC (8, 2) NULL,
    [ULWeightNormalRange]             NUMERIC (8, 2) NULL,
    [TBW]                             NUMERIC (8, 2) NULL,
    [LLTBW]                           NUMERIC (8, 2) NULL,
    [ULTBW]                           NUMERIC (8, 2) NULL,
    [ICW]                             NUMERIC (8, 2) NULL,
    [LLICW]                           NUMERIC (8, 2) NULL,
    [ULICW]                           NUMERIC (8, 2) NULL,
    [ECW]                             NUMERIC (8, 2) NULL,
    [LLECW]                           NUMERIC (8, 2) NULL,
    [ULECW]                           NUMERIC (8, 2) NULL,
    [Protein]                         NUMERIC (8, 2) NULL,
    [LLProtein]                       NUMERIC (8, 2) NULL,
    [ULProtein]                       NUMERIC (8, 2) NULL,
    [Minerals]                        NUMERIC (8, 2) NULL,
    [LLMinerals]                      NUMERIC (8, 2) NULL,
    [ULMinerals]                      NUMERIC (8, 2) NULL,
    [BFM]                             NUMERIC (8, 2) NULL,
    [LLBFM]                           NUMERIC (8, 2) NULL,
    [ULBFM]                           NUMERIC (8, 2) NULL,
    [SLM]                             NUMERIC (8, 2) NULL,
    [LLSLM]                           NUMERIC (8, 2) NULL,
    [ULSLM]                           NUMERIC (8, 2) NULL,
    [FFM]                             NUMERIC (8, 2) NULL,
    [LLFFM]                           NUMERIC (8, 2) NULL,
    [ULFFM]                           NUMERIC (8, 2) NULL,
    [SMM]                             NUMERIC (8, 2) NULL,
    [LLSMM]                           NUMERIC (8, 2) NULL,
    [ULSMM]                           NUMERIC (8, 2) NULL,
    [BMI]                             NUMERIC (8, 2) NULL,
    [LLBMI]                           NUMERIC (8, 2) NULL,
    [ULBMI]                           NUMERIC (8, 2) NULL,
    [PBF]                             NUMERIC (8, 2) NULL,
    [LLPBF]                           NUMERIC (8, 2) NULL,
    [ULPBF]                           NUMERIC (8, 2) NULL,
    [FFMRightArm]                     NUMERIC (8, 2) NULL,
    [LLFFMRightArm]                   NUMERIC (8, 2) NULL,
    [ULFFMRightArm]                   NUMERIC (8, 2) NULL,
    [FFMPercRightArm]                 NUMERIC (8, 2) NULL,
    [FFMLeftArm]                      NUMERIC (8, 2) NULL,
    [LLFFMLeftArm]                    NUMERIC (8, 2) NULL,
    [ULFFMLeftArm]                    NUMERIC (8, 2) NULL,
    [FFMPercLeftArm]                  NUMERIC (8, 2) NULL,
    [FFMTrunk]                        NUMERIC (8, 2) NULL,
    [LLFFMTrunk]                      NUMERIC (8, 2) NULL,
    [ULFFMTrunk]                      NUMERIC (8, 2) NULL,
    [FFMPercTrunk]                    NUMERIC (8, 2) NULL,
    [FFMRightLeg]                     NUMERIC (8, 2) NULL,
    [LLFFMRightLeg]                   NUMERIC (8, 2) NULL,
    [ULFFMRightLeg]                   NUMERIC (8, 2) NULL,
    [FFMPercRightLeg]                 NUMERIC (8, 2) NULL,
    [FFMLeftLeg]                      NUMERIC (8, 2) NULL,
    [LLFFMLeftLeg]                    NUMERIC (8, 2) NULL,
    [ULFFMLeftLeg]                    NUMERIC (8, 2) NULL,
    [FFMPercLeftLeg]                  NUMERIC (8, 2) NULL,
    [ECWTBW]                          NUMERIC (8, 2) NULL,
    [BFMRightArm]                     NUMERIC (8, 2) NULL,
    [BFMPercRightArm]                 NUMERIC (8, 2) NULL,
    [BFMLeftArm]                      NUMERIC (8, 2) NULL,
    [BFMPercLeftArm]                  NUMERIC (8, 2) NULL,
    [BFMTrunk]                        NUMERIC (8, 2) NULL,
    [BFMPercTrunk]                    NUMERIC (8, 2) NULL,
    [BFMRightLeg]                     NUMERIC (8, 2) NULL,
    [BFMPercRightLeg]                 NUMERIC (8, 2) NULL,
    [BFMLeftLeg]                      NUMERIC (8, 2) NULL,
    [BFMPercLeftLeg]                  NUMERIC (8, 2) NULL,
    [InBodyScore]                     NUMERIC (8, 2) NULL,
    [TargetWeight]                    NUMERIC (8, 2) NULL,
    [WeightControl]                   NUMERIC (8, 2) NULL,
    [BFMControl]                      NUMERIC (8, 2) NULL,
    [FFMControl]                      NUMERIC (8, 2) NULL,
    [BMR]                             NUMERIC (8, 2) NULL,
    [WHR]                             NUMERIC (8, 2) NULL,
    [LLWHR]                           NUMERIC (8, 2) NULL,
    [ULWHR]                           NUMERIC (8, 2) NULL,
    [VFL]                             INT            NULL,
    [ObesityDegree]                   NUMERIC (8, 2) NULL,
    [LLObesityDegree]                 NUMERIC (8, 2) NULL,
    [ULObesityDegree]                 NUMERIC (8, 2) NULL,
    [BCM]                             NUMERIC (8, 2) NULL,
    [LLBCM]                           NUMERIC (8, 2) NULL,
    [ULBCM]                           NUMERIC (8, 2) NULL,
    [AC]                              NUMERIC (8, 2) NULL,
    [AMC]                             NUMERIC (8, 2) NULL,
    [BMC]                             NUMERIC (8, 2) NULL,
    [LLBMC]                           NUMERIC (8, 2) NULL,
    [ULBMC]                           NUMERIC (8, 2) NULL,
    [5kHzRAImpedance]                 NUMERIC (8, 2) NULL,
    [5kHzLAImpedance]                 NUMERIC (8, 2) NULL,
    [5kHzTRImpedance]                 NUMERIC (8, 2) NULL,
    [5kHzRLImpedance]                 NUMERIC (8, 2) NULL,
    [5kHzLLImpedance]                 NUMERIC (8, 2) NULL,
    [50kHzRAImpedance]                NUMERIC (8, 2) NULL,
    [50kHzLAImpedance]                NUMERIC (8, 2) NULL,
    [50kHzTRImpedance]                NUMERIC (8, 2) NULL,
    [50kHzRLImpedance]                NUMERIC (8, 2) NULL,
    [50kHzLLImpedance]                NUMERIC (8, 2) NULL,
    [500kHzRAImpedance]               NUMERIC (8, 2) NULL,
    [500kHzLAImpedance]               NUMERIC (8, 2) NULL,
    [500kHzTRImpedance]               NUMERIC (8, 2) NULL,
    [500kHzRLImpedance]               NUMERIC (8, 2) NULL,
    [500kHzLLImpedance]               NUMERIC (8, 2) NULL,
    [MCNeck]                          NUMERIC (8, 2) NULL,
    [MCChest]                         NUMERIC (8, 2) NULL,
    [MCAbdomen]                       NUMERIC (8, 2) NULL,
    [MCHip]                           NUMERIC (8, 2) NULL,
    [MCRightArm]                      NUMERIC (8, 2) NULL,
    [MCLeftArm]                       NUMERIC (8, 2) NULL,
    [MCRightThigh]                    NUMERIC (8, 2) NULL,
    [MCLeftThigh]                     NUMERIC (8, 2) NULL,
    [GrowthScore]                     NUMERIC (8, 2) NULL,
    [ObesityDegreeChild]              NUMERIC (8, 2) NULL,
    [LLObesityDegreeChildNormalRange] NUMERIC (8, 2) NULL,
    [ULObesityDegreeChildNormalRange] NUMERIC (8, 2) NULL,
    [Systolic]                        NUMERIC (8, 2) NULL,
    [Diastolic]                       NUMERIC (8, 2) NULL,
    [Pulse]                           NUMERIC (8, 2) NULL,
    [MeanArteryPressure]              NUMERIC (8, 2) NULL,
    [PulsePressure]                   NUMERIC (8, 2) NULL,
    [RatePressureProduct]             NUMERIC (8, 2) NULL,
    [SMI]                             NUMERIC (8, 2) NULL,
    [CreatedById]                     INT            NOT NULL,
    [DateCreated]                     DATETIME       NOT NULL,
    [ModifiedById]                    INT            NULL,
    [DateModified]                    DATETIME       NULL,
    [TimeStamp]                       ROWVERSION     NOT NULL,
    [IsHidden]                        BIT            CONSTRAINT [DF_Scan_IsHidden] DEFAULT ((0)) NOT NULL,
    [BillStatus]                      TINYINT        CONSTRAINT [DF_Scan_BillStatus] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Scans] PRIMARY KEY CLUSTERED ([ScanId] ASC),
    CONSTRAINT [FK_ScanGender] FOREIGN KEY ([GenderId]) REFERENCES [dbo].[Gender] ([GenderId]),
    CONSTRAINT [FK_ScanImport] FOREIGN KEY ([ScansImportId]) REFERENCES [dbo].[ScansImport] ([ScansImportId]),
    CONSTRAINT [FK_ScanMember] FOREIGN KEY ([MemberId]) REFERENCES [dbo].[Member] ([MemberId]),
    CONSTRAINT [FK_ScanUserCreated] FOREIGN KEY ([CreatedById]) REFERENCES [dbo].[AppUser] ([AppUserId]),
    CONSTRAINT [FK_ScanUserModified] FOREIGN KEY ([ModifiedById]) REFERENCES [dbo].[AppUser] ([AppUserId])
);







