namespace DataService.ViewModels
{
    public class ScanCSVViewModel
    {
   
        public string MobileNumber { get; set; }
        public string Height { get; set; }
        public string Gender { get; set; }
        public string Age { get; set; }
        public string TestDateTime { get; set; }
        public string Weight { get; set; }
        public string LlweightNormalRange { get; set; }
        public string UlweightNormalRange { get; set; }
        public string Tbw { get; set; }
        public string Lltbw { get; set; }
        public string Ultbw { get; set; }
        public string Icw { get; set; }
        public string Llicw { get; set; }
        public string Ulicw { get; set; }
        public string Ecw { get; set; }
        public string Llecw { get; set; }
        public string Ulecw { get; set; }
        public string Protein { get; set; }
        public string Llprotein { get; set; }
        public string Ulprotein { get; set; }
        public string Minerals { get; set; }
        public string Llminerals { get; set; }
        public string Ulminerals { get; set; }
        public string Bfm { get; set; }
        public string Llbfm { get; set; }
        public string Ulbfm { get; set; }
        public string Slm { get; set; }
        public string Llslm { get; set; }
        public string Ulslm { get; set; }
        public string Ffm { get; set; }
        public string Llffm { get; set; }
        public string Ulffm { get; set; }
        public string Smm { get; set; }
        public string Llsmm { get; set; }
        public string Ulsmm { get; set; }
        public string Bmi { get; set; }
        public string Llbmi { get; set; }
        public string Ulbmi { get; set; }
        public string Pbf { get; set; }
        public string Llpbf { get; set; }
        public string Ulpbf { get; set; }
        public string FfmrightArm { get; set; }
        public string LlffmrightArm { get; set; }
        public string UlffmrightArm { get; set; }
        public string FfmpercRightArm { get; set; }
        public string FfmleftArm { get; set; }
        public string LlffmleftArm { get; set; }
        public string UlffmleftArm { get; set; }
        public string FfmpercLeftArm { get; set; }
        public string Ffmtrunk { get; set; }
        public string Llffmtrunk { get; set; }
        public string Ulffmtrunk { get; set; }
        public string FfmpercTrunk { get; set; }
        public string FfmrightLeg { get; set; }
        public string LlffmrightLeg { get; set; }
        public string UlffmrightLeg { get; set; }
        public string FfmpercRightLeg { get; set; }
        public string FfmleftLeg { get; set; }
        public string LlffmleftLeg { get; set; }
        public string UlffmleftLeg { get; set; }
        public string FfmpercLeftLeg { get; set; }
        public string Ecwtbw { get; set; }
        public string BfmrightArm { get; set; }
        public string BfmpercRightArm { get; set; }
        public string BfmleftArm { get; set; }
        public string BfmpercLeftArm { get; set; }
        public string Bfmtrunk { get; set; }
        public string BfmpercTrunk { get; set; }
        public string BfmrightLeg { get; set; }
        public string BfmpercRightLeg { get; set; }
        public string BfmleftLeg { get; set; }
        public string BfmpercLeftLeg { get; set; }
        public string InBodyScore { get; set; }
        public string TargetWeight { get; set; }
        public string WeightControl { get; set; }
        public string Bfmcontrol { get; set; }
        public string Ffmcontrol { get; set; }
        public string Bmr { get; set; }
        public string Whr { get; set; }
        public string Llwhr { get; set; }
        public string Ulwhr { get; set; }
        public string Vfl { get; set; }
        public string ObesityDegree { get; set; }
        public string LlobesityDegree { get; set; }
        public string UlobesityDegree { get; set; }
        public string Bcm { get; set; }
        public string Llbcm { get; set; }
        public string Ulbcm { get; set; }
        public string Ac { get; set; }
        public string Amc { get; set; }
        public string Bmc { get; set; }
        public string Llbmc { get; set; }
        public string Ulbmc { get; set; }
        public string _5kHzRaimpedance { get; set; }
        public string _5kHzLaimpedance { get; set; }
        public string _5kHzTrimpedance { get; set; }
        public string _5kHzRlimpedance { get; set; }
        public string _5kHzLlimpedance { get; set; }
        public string _50kHzRaimpedance { get; set; }
        public string _50kHzLaimpedance { get; set; }
        public string _50kHzTrimpedance { get; set; }
        public string _50kHzRlimpedance { get; set; }
        public string _50kHzLlimpedance { get; set; }
        public string _500kHzRaimpedance { get; set; }
        public string _500kHzLaimpedance { get; set; }
        public string _500kHzTrimpedance { get; set; }
        public string _500kHzRlimpedance { get; set; }
        public string _500kHzLlimpedance { get; set; }
        public string Mcneck { get; set; }
        public string Mcchest { get; set; }
        public string Mcabdomen { get; set; }
        public string Mchip { get; set; }
        public string McrightArm { get; set; }
        public string McleftArm { get; set; }
        public string McrightThigh { get; set; }
        public string McleftThigh { get; set; }
        public string GrowthScore { get; set; }
        public string ObesityDegreeChild { get; set; }
        public string LlobesityDegreeChildNormalRange { get; set; }
        public string UlobesityDegreeChildNormalRange { get; set; }
        public string Systolic { get; set; }
        public string Diastolic { get; set; }
        public string Pulse { get; set; }
        public string MeanArteryPressure { get; set; }
        public string PulsePressure { get; set; }
        public string RatePressureProduct { get; set; }
        public string Smi { get; set; }
    }
}
